spack:
  config:
    install_tree:
      root: $spack/..
      projections:
        all: '{compiler.name}-{compiler.version}/{name}-{version}-{hash}'
    misc_cache: $spack/../misc_cache
    test_stage: $spack/../test_stage
    build_stage::
    - $spack/../build_stage

  # Regular TPLs do not need views
  view: false

  compilers::
  - compiler:
      environment: {}
      extra_rpaths: []
      flags:
        fflags: -Mfreeform
      modules: []
      operating_system: rhel8
      paths:
        cc: /opt/rocm-5.6.0/llvm/bin/amdclang
        cxx: /opt/rocm-5.6.0/llvm/bin/amdclang++
        f77: /opt/rocm-5.6.0/llvm/bin/amdflang
        fc: /opt/rocm-5.6.0/llvm/bin/amdflang
      spec: clang@16.0.0
      target: x86_64

  packages:
    all:
      compiler: [gcc, intel, pgi, clang, xl, nag]
      providers:
        blas: [openblas]
        lapack: [netlib-lapack]
        gl: [opengl]
        glu: [openglu]
        zlib-api: [zlib]
        mpi: [cray-mpich]

    openblas:
      buildable: false
      externals:
      - prefix: /usr
        spec: openblas@0.3.15
    opengl:
      buildable: false
      externals:
      - spec: opengl@1.7.0
        prefix: /usr
    openglu:
      buildable: false
      externals:
      - spec: openglu@1.3.1
        prefix: /usr

    hip:
      version: [5.6.0]
      buildable: false
      externals:
      - spec: hip@5.6.0
        prefix: /opt/rocm-5.6.0/hip

    llvm-amdgpu:
      version: [5.6.0]
      buildable: false
      externals:
      - spec: llvm-amdgpu@5.6.0
        prefix: /opt/rocm-5.6.0/llvm

    hsa-rocr-dev:
      version: [5.6.0]
      buildable: false
      externals:
      - spec: hsa-rocr-dev@5.6.0
        prefix: /opt/rocm-5.6.0/

    rocblas:
      version: [5.6.0]
      buildable: false
      externals:
      - spec: rocblas@5.6.0
        prefix: /opt/rocm-5.6.0/

    rocminfo:
      version: [5.6.0]
      buildable: false
      externals:
      - spec: rocminfo@5.6.0
        prefix: /opt/rocm-5.6.0/

    rocprim:
      version: [5.6.0]
      buildable: false
      externals:
      - spec: rocprim@5.6.0
        prefix: /opt/rocm-5.6.0/

    rocm-device-libs:
      version: [5.6.0]
      buildable: false
      externals:
      - spec: rocm-device-libs@5.6.0
        prefix: /opt/rocm-5.6.0/

    # Lock down which MPI we are using
    mpi:
      buildable: false
    cray-mpich:
      buildable: false
      externals:
      - spec: cray-mpich@8.1.25%clang@16.0.0+slurm
        prefix: /usr/tce/packages/cray-mpich-tce/cray-mpich-8.1.25-rocmcc-5.6.0/

    netlib-lapack:
      buildable: false
      externals:
      - spec: netlib-lapack@3.8.0
        prefix: /usr

    # System level packages to not build
    autoconf:
      buildable: false
      externals:
      - spec: autoconf@2.69
        prefix: /usr
    automake:
      buildable: false
      externals:
      - spec: automake@1.61.1
        prefix: /usr
    binutils:
      buildable: false
      externals:
      - spec: binutils@2.30
        prefix: /usr
    bison:
      buildable: false
      externals:
      - spec: bison@3.0.4
        prefix: /usr
    bzip2:
      buildable: false
      externals:
      - spec: bzip2@1.0.6
        prefix: /usr
    curl:
      buildable: false
      externals:
      - spec: curl@7.29.0
        prefix: /usr
    diffutils:
      buildable: false
      externals:
      - spec: diffutils@3.6
        prefix: /usr
    elfutils:
      buildable: false
      externals:
      - spec: elfutils@0.187
        prefix: /usr
    expat:
      buildable: false
      externals:
      - spec: expat@2.2.5
        prefix: /usr
    libepoxy:
      buildable: false
      externals:
      - spec: libepoxy@1.5.8
        prefix: /usr
    flex:
      buildable: false
      externals:
      - spec: flex@2.6.1
        prefix: /usr
    findutils:
      buildable: false
      externals:
      - spec: findutils@4.6.0
        prefix: /usr
    gettext:
      buildable: false
      externals:
      - spec: gettext@0.19.8.1
        prefix: /usr
    ghostscript:
      buildable: false
      externals:
      - spec: ghostscript@9.27
        prefix: /usr
    git:
      buildable: false
      externals:
      - spec: git@2
        prefix: /usr
    gmake:
      buildable: false
      externals:
      - spec: gmake@4.2.1
        prefix: /usr
    graphviz:
      buildable: false
      externals:
      - spec: graphviz@2.40.1
        prefix: /usr
    groff:
      buildable: false
      externals:
      - spec: groff@1.22.2
        prefix: /usr
    hwloc:
      buildable: false
      externals:
      - spec: hwloc@2.9.0
        prefix: /usr
    libtool:
      buildable: false
      externals:
      - spec: libtool@2.4.6
        prefix: /usr
    # NOTE: removed since fails on clang builds
    # libunwind:
    #   buildable: false
    #   externals:
    #   - spec: libunwind@1.3.1
    #     prefix: /usr
    libx11:
      buildable: false
      externals:
      - spec: libx11@1.6.8
        prefix: /usr
    lua:
      buildable: false
      externals:
      - spec: lua@5.3.4
        prefix: /usr
    m4:
      buildable: false
      externals:
      - spec: m4@1.4.18
        prefix: /usr
    ninja:
      buildable: false
      externals:
      - spec: ninja@1.11.0
        prefix: /usr/tce/packages/ninja/ninja-1.11.0
    openssl:
      buildable: false
      externals:
      - spec: openssl@1.1.1k
        prefix: /usr
    perl:
      buildable: false
      externals:
      - spec: perl@5.26.3
        prefix: /usr
    pkg-config:
      buildable: false
      externals:
      - spec: pkg-config@1.4.2
        prefix: /usr
    readline:
      buildable: false
      externals:
      - spec: readline@7.0
        prefix: /usr
    swig:
      buildable: false
      externals:
      - spec: swig@3.0.12
        prefix: /usr
    tar:
      buildable: false
      externals:
      - spec: tar@1.30
        prefix: /usr
    unzip:
      buildable: false
      externals:
      - spec: unzip@6.0
        prefix: /usr
    zlib:
      buildable: false
      externals:
      - spec: zlib@1.2.11
        prefix: /usr

    # Lock in versions of Devtools
    cmake:
      version: [3.23.1]
      buildable: false
      externals:
      - spec: cmake@3.23.1
        prefix: /usr/tce
    cppcheck:
      version: [2.9]
      buildable: false
      externals:
      - spec: cppcheck@2.9
        prefix: /usr/workspace/smithdev/devtools/toss_4_x86_64_ib_cray/latest/cppcheck-2.9
    doxygen:
      version: [1.9.8]
      buildable: false
      externals:
      - spec: doxygen@1.9.8
        prefix: /usr/workspace/smithdev/devtools/toss_4_x86_64_ib_cray/latest/doxygen-1.9.8
    py-ats:
      version: [7.0.105]
      buildable: false
      externals:
      - spec: py-ats@7.0.105
        prefix: /usr/workspace/smithdev/devtools/toss_4_x86_64_ib_cray/latest/python-3.11.7
    py-sphinx:
      version: [7.2.6]
      buildable: false
      externals:
      - spec: py-sphinx@7.2.6
        prefix: /usr/workspace/smithdev/devtools/toss_4_x86_64_ib_cray/latest/python-3.11.7
    python:
      buildable: false
      externals:
      - spec: python@3.9.12
        prefix: /usr/tce/packages/python/python-3.9.12

    # Globally lock version of third party libraries
    axom:
      require: "@0.9.0.1"
    camp:
      require: "@2024.02.0"
    conduit:
      require: "@0.9.1~shared~test~examples~utilities"
    hdf5:
      variants: ~shared~mpi
    mfem:
      require: "@4.7.0.1"
    raja:
      require: "@2024.02.0~shared~examples~exercises"
    tribol:
      require: "@0.1.0.16~examples~tests"
    umpire:
      require: "@2024.02.0~shared~examples~werror"
