spack:
  config:
    install_tree:
      root: $spack/..
      projections:
        all: '{compiler.name}-{compiler.version}/{name}-{version}-{hash}'
    misc_cache: $spack/../misc_cache
    test_stage: $spack/../test_stage
    build_stage::
    - $spack/../build_stage

  # Regular TPLs do not need views
  view: false

  compilers::
  - compiler:
      environment: {}
      extra_rpaths: []
      flags: {}
      modules: []
      operating_system: rhel8
      paths:
        cc: /opt/rocm-6.1.2/llvm/bin/amdclang
        cxx: /opt/rocm-6.1.2/llvm/bin/amdclang++
        f77: /opt/rocm-6.1.2/llvm/bin/amdflang
        fc: /opt/rocm-6.1.2/llvm/bin/amdflang
      spec: clang@17.0.0
      target: x86_64

  packages:
    all:
      providers:
        blas: [openblas]
        lapack: [netlib-lapack]
        gl: [opengl]
        glu: [openglu]
        zlib-api: [zlib]
        mpi: [cray-mpich]

    # Providers
    openblas:
      buildable: false
      externals:
      - prefix: /usr
        spec: openblas@0.3.15
    opengl:
      buildable: false
      externals:
      - spec: opengl@1.7.0
        prefix: /usr
    openglu:
      buildable: false
      externals:
      - spec: openglu@1.3.1
        prefix: /usr
    netlib-lapack:
      buildable: false
      externals:
      - spec: netlib-lapack@3.8.0
        prefix: /usr
    zlib:
      buildable: false
      externals:
      - spec: zlib@1.2.11
        prefix: /usr

    # Lock down which MPI we are using
    mpi:
      buildable: false
    cray-mpich:
      buildable: false
      externals:
      - spec: cray-mpich@8.1.30
        prefix: /usr/tce/packages/cray-mpich-tce/cray-mpich-8.1.30-rocmcc-6.1.2

    # ROCm
    hip:
      buildable: false
      externals:
      - spec: hip@6.1.2
        prefix: /opt/rocm-6.1.2/
    hipblas:
      buildable: false
      externals:
      - spec: hipblas@6.1.2
        prefix: /opt/rocm-6.1.2/
    hipsolver:
      buildable: false
      externals:
      - spec: hipsolver@6.1.2
        prefix: /opt/rocm-6.1.2/
    hipsparse:
      buildable: false
      externals:
      - spec: hipsparse@6.1.2
        prefix: /opt/rocm-6.1.2/
    llvm-amdgpu:
      buildable: false
      externals:
      - spec: llvm-amdgpu@6.1.2
        prefix: /opt/rocm-6.1.2/llvm
    hsa-rocr-dev:
      buildable: false
      externals:
      - spec: hsa-rocr-dev@6.1.2
        prefix: /opt/rocm-6.1.2/
    rocblas:
      buildable: false
      externals:
      - spec: rocblas@6.1.2
        prefix: /opt/rocm-6.1.2/
    rocm-core:
      buildable: false
      externals:
      - spec: rocm-core@6.1.2
        prefix: /opt/rocm-6.1.2/
    rocrand:
      buildable: false
      externals:
      - spec: rocrand@6.1.2
        prefix: /opt/rocm-6.1.2/
    rocminfo:
      buildable: false
      externals:
      - spec: rocminfo@6.1.2
        prefix: /opt/rocm-6.1.2/
    rocsolver:
      buildable: false
      externals:
      - spec: rocsolver@6.1.2
        prefix: /opt/rocm-6.1.2/
    rocsparse:
      buildable: false
      externals:
      - spec: rocsparse@6.1.2
        prefix: /opt/rocm-6.1.2/
    rocthrust:
      buildable: false
      externals:
      - spec: rocthrust@6.1.2
        prefix: /opt/rocm-6.1.2/
    rocprim:
      buildable: false
      externals:
      - spec: rocprim@6.1.2
        prefix: /opt/rocm-6.1.2/
    rocm-device-libs:
      buildable: false
      externals:
      - spec: rocm-device-libs@6.1.2
        prefix: /opt/rocm-6.1.2/

    # System level packages to not build
    autoconf:
      buildable: false
      externals:
      - spec: autoconf@2.69
        prefix: /usr
    automake:
      buildable: false
      externals:
      - spec: automake@1.61.1
        prefix: /usr
    binutils:
      buildable: false
      externals:
      - spec: binutils@2.30
        prefix: /usr
    bison:
      buildable: false
      externals:
      - spec: bison@3.0.4
        prefix: /usr
    bzip2:
      buildable: false
      externals:
      - spec: bzip2@1.0.6
        prefix: /usr
    curl:
      buildable: false
      externals:
      - spec: curl@7.29.0
        prefix: /usr
    diffutils:
      buildable: false
      externals:
      - spec: diffutils@3.6
        prefix: /usr
    elfutils:
      buildable: false
      externals:
      - spec: elfutils@0.187
        prefix: /usr
    expat:
      buildable: false
      externals:
      - spec: expat@2.2.5
        prefix: /usr
    libepoxy:
      buildable: false
      externals:
      - spec: libepoxy@1.5.8
        prefix: /usr
    flex:
      buildable: false
      externals:
      - spec: flex@2.6.1
        prefix: /usr
    findutils:
      buildable: false
      externals:
      - spec: findutils@4.6.0
        prefix: /usr
    gettext:
      buildable: false
      externals:
      - spec: gettext@0.19.8.1
        prefix: /usr
    ghostscript:
      buildable: false
      externals:
      - spec: ghostscript@9.27
        prefix: /usr
    git:
      buildable: false
      externals:
      - spec: git@2
        prefix: /usr
    gmake:
      buildable: false
      externals:
      - spec: gmake@4.2.1
        prefix: /usr
    graphviz:
      buildable: false
      externals:
      - spec: graphviz@2.40.1
        prefix: /usr
    groff:
      buildable: false
      externals:
      - spec: groff@1.22.2
        prefix: /usr
    hwloc:
      buildable: false
      externals:
      - spec: hwloc@2.9.0
        prefix: /usr
    libtool:
      buildable: false
      externals:
      - spec: libtool@2.4.6
        prefix: /usr
    # NOTE: removed since fails on clang builds
    # libunwind:
    #   buildable: false
    #   externals:
    #   - spec: libunwind@1.3.1
    #     prefix: /usr
    libx11:
      buildable: false
      externals:
      - spec: libx11@1.6.8
        prefix: /usr
    lua:
      buildable: false
      externals:
      - spec: lua@5.3.4
        prefix: /usr
    m4:
      buildable: false
      externals:
      - spec: m4@1.4.18
        prefix: /usr
    ninja:
      buildable: false
      externals:
      - spec: ninja@1.11.0
        prefix: /usr/tce/packages/ninja/ninja-1.11.0
    openssl:
      buildable: false
      externals:
      - spec: openssl@1.1.1k
        prefix: /usr
    perl:
      buildable: false
      externals:
      - spec: perl@5.26.3
        prefix: /usr
    pkg-config:
      buildable: false
      externals:
      - spec: pkg-config@1.4.2
        prefix: /usr
    pkgconf:
      buildable: false
      externals:
      - spec: pkgconf@1.4.2
        prefix: /usr
    readline:
      buildable: false
      externals:
      - spec: readline@7.0
        prefix: /usr
    swig:
      buildable: false
      externals:
      - spec: swig@3.0.12
        prefix: /usr
    tar:
      buildable: false
      externals:
      - spec: tar@1.30
        prefix: /usr
    unzip:
      buildable: false
      externals:
      - spec: unzip@6.0
        prefix: /usr

    # Lock in versions of Devtools
    cmake:
      version: [3.23.1]
      buildable: false
      externals:
      - spec: cmake@3.23.1
        prefix: /usr/tce
    python:
      buildable: false
      externals:
      - spec: python@3.9.12
        prefix: /usr/tce/packages/python/python-3.9.12

    # Globally lock version of third party libraries
    axom:
      require: "@0.9.0.1"
    adiak:
      require: "@0.4.0"
    caliper:
      require: "@2.10.0~kokkos"
    camp:
      require: "@2024.02.0"
    conduit:
      require: "@0.9.1~shared~test~examples~utilities"
    hdf5:
      variants: ~shared~mpi
    mfem:
      require: "@4.7.0.1"
    raja:
      require: "@2024.02.0~shared~examples~exercises"
    tribol:
      require: "@0.1.0.16~examples~tests"
    umpire:
      require: "@2024.02.0~shared~examples~werror"
