name: Build and Test

on: pull_request

# strategy:
#   matrix:
#     VM_IMAGENAME: [ ubuntu-22.04 ]
#     COMPILER_TYPE: [ clang, gcc, cuda ]
#     TEST_TARGET: [ linux_clang14 ]
#     HOST_CONFIG: [ clang@14.0.0.cmake ]
#     BUILD_TYPE: [ Debug, Release ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: seracllnl/tpls:clang-14_08-15-24_21h-49m
      env:
        BUILD_SRC_OPTS: ""
        BUILD_TYPE: Release
        CMAKE_OPTS: -DBUILD_SHARED_LIBS=ON
        HOST_CONFIG: clang@14.0.0.cmake
      volumes:
      - /home/serac/serac
    steps:
      - uses: actions/checkout@v4
        with: 
          submodules: recursive
      - name: Build and Test
        run: |
          ls
          pwd
          ./scripts/llnl/build_src.py $BUILD_SRC_OPTS --verbose \
            --host-config $HOST_CONFIG \
            --extra-cmake-options "${CMAKE_OPTS} -DCMAKE_BUILD_TYPE=$BUILD_TYPE" \
            --jobs 4
